// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/fleet/internal/client (interfaces: GetterInterface)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/client_getter_mock.go -package=mocks -mock_names=GetterInterface=MockClientGetter github.com/rancher/fleet/internal/client GetterInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	client "github.com/rancher/fleet/internal/client"
	gomock "go.uber.org/mock/gomock"
)

// MockClientGetter is a mock of GetterInterface interface.
type MockClientGetter struct {
	ctrl     *gomock.Controller
	recorder *MockClientGetterMockRecorder
	isgomock struct{}
}

// MockClientGetterMockRecorder is the mock recorder for MockClientGetter.
type MockClientGetterMockRecorder struct {
	mock *MockClientGetter
}

// NewMockClientGetter creates a new mock instance.
func NewMockClientGetter(ctrl *gomock.Controller) *MockClientGetter {
	mock := &MockClientGetter{ctrl: ctrl}
	mock.recorder = &MockClientGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientGetter) EXPECT() *MockClientGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClientGetter) Get() (*client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientGetterMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientGetter)(nil).Get))
}

// GetNamespace mocks base method.
func (m *MockClientGetter) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockClientGetterMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockClientGetter)(nil).GetNamespace))
}
