// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1 (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/fleet_controllers_mock.go -package=mocks -mock_names=Interface=MockFleetControllers github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1 Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1alpha1 "github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockFleetControllers is a mock of Interface interface.
type MockFleetControllers struct {
	ctrl     *gomock.Controller
	recorder *MockFleetControllersMockRecorder
	isgomock struct{}
}

// MockFleetControllersMockRecorder is the mock recorder for MockFleetControllers.
type MockFleetControllersMockRecorder struct {
	mock *MockFleetControllers
}

// NewMockFleetControllers creates a new mock instance.
func NewMockFleetControllers(ctrl *gomock.Controller) *MockFleetControllers {
	mock := &MockFleetControllers{ctrl: ctrl}
	mock.recorder = &MockFleetControllersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFleetControllers) EXPECT() *MockFleetControllersMockRecorder {
	return m.recorder
}

// Bundle mocks base method.
func (m *MockFleetControllers) Bundle() v1alpha1.BundleController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bundle")
	ret0, _ := ret[0].(v1alpha1.BundleController)
	return ret0
}

// Bundle indicates an expected call of Bundle.
func (mr *MockFleetControllersMockRecorder) Bundle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bundle", reflect.TypeOf((*MockFleetControllers)(nil).Bundle))
}

// BundleDeployment mocks base method.
func (m *MockFleetControllers) BundleDeployment() v1alpha1.BundleDeploymentController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BundleDeployment")
	ret0, _ := ret[0].(v1alpha1.BundleDeploymentController)
	return ret0
}

// BundleDeployment indicates an expected call of BundleDeployment.
func (mr *MockFleetControllersMockRecorder) BundleDeployment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BundleDeployment", reflect.TypeOf((*MockFleetControllers)(nil).BundleDeployment))
}

// BundleNamespaceMapping mocks base method.
func (m *MockFleetControllers) BundleNamespaceMapping() v1alpha1.BundleNamespaceMappingController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BundleNamespaceMapping")
	ret0, _ := ret[0].(v1alpha1.BundleNamespaceMappingController)
	return ret0
}

// BundleNamespaceMapping indicates an expected call of BundleNamespaceMapping.
func (mr *MockFleetControllersMockRecorder) BundleNamespaceMapping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BundleNamespaceMapping", reflect.TypeOf((*MockFleetControllers)(nil).BundleNamespaceMapping))
}

// Cluster mocks base method.
func (m *MockFleetControllers) Cluster() v1alpha1.ClusterController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cluster")
	ret0, _ := ret[0].(v1alpha1.ClusterController)
	return ret0
}

// Cluster indicates an expected call of Cluster.
func (mr *MockFleetControllersMockRecorder) Cluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cluster", reflect.TypeOf((*MockFleetControllers)(nil).Cluster))
}

// ClusterGroup mocks base method.
func (m *MockFleetControllers) ClusterGroup() v1alpha1.ClusterGroupController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterGroup")
	ret0, _ := ret[0].(v1alpha1.ClusterGroupController)
	return ret0
}

// ClusterGroup indicates an expected call of ClusterGroup.
func (mr *MockFleetControllersMockRecorder) ClusterGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterGroup", reflect.TypeOf((*MockFleetControllers)(nil).ClusterGroup))
}

// ClusterRegistration mocks base method.
func (m *MockFleetControllers) ClusterRegistration() v1alpha1.ClusterRegistrationController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterRegistration")
	ret0, _ := ret[0].(v1alpha1.ClusterRegistrationController)
	return ret0
}

// ClusterRegistration indicates an expected call of ClusterRegistration.
func (mr *MockFleetControllersMockRecorder) ClusterRegistration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterRegistration", reflect.TypeOf((*MockFleetControllers)(nil).ClusterRegistration))
}

// ClusterRegistrationToken mocks base method.
func (m *MockFleetControllers) ClusterRegistrationToken() v1alpha1.ClusterRegistrationTokenController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterRegistrationToken")
	ret0, _ := ret[0].(v1alpha1.ClusterRegistrationTokenController)
	return ret0
}

// ClusterRegistrationToken indicates an expected call of ClusterRegistrationToken.
func (mr *MockFleetControllersMockRecorder) ClusterRegistrationToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterRegistrationToken", reflect.TypeOf((*MockFleetControllers)(nil).ClusterRegistrationToken))
}

// Content mocks base method.
func (m *MockFleetControllers) Content() v1alpha1.ContentController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].(v1alpha1.ContentController)
	return ret0
}

// Content indicates an expected call of Content.
func (mr *MockFleetControllersMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockFleetControllers)(nil).Content))
}

// GitRepo mocks base method.
func (m *MockFleetControllers) GitRepo() v1alpha1.GitRepoController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitRepo")
	ret0, _ := ret[0].(v1alpha1.GitRepoController)
	return ret0
}

// GitRepo indicates an expected call of GitRepo.
func (mr *MockFleetControllersMockRecorder) GitRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitRepo", reflect.TypeOf((*MockFleetControllers)(nil).GitRepo))
}

// GitRepoRestriction mocks base method.
func (m *MockFleetControllers) GitRepoRestriction() v1alpha1.GitRepoRestrictionController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitRepoRestriction")
	ret0, _ := ret[0].(v1alpha1.GitRepoRestrictionController)
	return ret0
}

// GitRepoRestriction indicates an expected call of GitRepoRestriction.
func (mr *MockFleetControllersMockRecorder) GitRepoRestriction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitRepoRestriction", reflect.TypeOf((*MockFleetControllers)(nil).GitRepoRestriction))
}

// HelmOp mocks base method.
func (m *MockFleetControllers) HelmOp() v1alpha1.HelmOpController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HelmOp")
	ret0, _ := ret[0].(v1alpha1.HelmOpController)
	return ret0
}

// HelmOp indicates an expected call of HelmOp.
func (mr *MockFleetControllersMockRecorder) HelmOp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HelmOp", reflect.TypeOf((*MockFleetControllers)(nil).HelmOp))
}

// ImageScan mocks base method.
func (m *MockFleetControllers) ImageScan() v1alpha1.ImageScanController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageScan")
	ret0, _ := ret[0].(v1alpha1.ImageScanController)
	return ret0
}

// ImageScan indicates an expected call of ImageScan.
func (mr *MockFleetControllersMockRecorder) ImageScan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageScan", reflect.TypeOf((*MockFleetControllers)(nil).ImageScan))
}

// Policy mocks base method.
func (m *MockFleetControllers) Policy() v1alpha1.PolicyController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Policy")
	ret0, _ := ret[0].(v1alpha1.PolicyController)
	return ret0
}

// Policy indicates an expected call of Policy.
func (mr *MockFleetControllersMockRecorder) Policy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Policy", reflect.TypeOf((*MockFleetControllers)(nil).Policy))
}

// Schedule mocks base method.
func (m *MockFleetControllers) Schedule() v1alpha1.ScheduleController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule")
	ret0, _ := ret[0].(v1alpha1.ScheduleController)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockFleetControllersMockRecorder) Schedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockFleetControllers)(nil).Schedule))
}
