// Code generated by MockGen. DO NOT EDIT.
// Source: fetcher.go
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -source=fetcher.go -destination=../../../../mocks/git_fetcher_mock.go -package=mocks github.com/rancher/fleet/internal/cmd/cli/gitcloner/submodule Strategy,CapabilityDetector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	git "github.com/go-git/go-git/v5"
	plumbing "github.com/go-git/go-git/v5/plumbing"
	transport "github.com/go-git/go-git/v5/plumbing/transport"
	capability "github.com/rancher/fleet/internal/cmd/cli/gitcloner/submodule/capability"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
	isgomock struct{}
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockStrategy) Execute(ctx context.Context, r *git.Repository, CommitHash plumbing.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, r, CommitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockStrategyMockRecorder) Execute(ctx, r, CommitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockStrategy)(nil).Execute), ctx, r, CommitHash)
}

// Type mocks base method.
func (m *MockStrategy) Type() capability.StrategyType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(capability.StrategyType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockStrategyMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockStrategy)(nil).Type))
}

// MockCapabilityDetector is a mock of CapabilityDetector interface.
type MockCapabilityDetector struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilityDetectorMockRecorder
	isgomock struct{}
}

// MockCapabilityDetectorMockRecorder is the mock recorder for MockCapabilityDetector.
type MockCapabilityDetectorMockRecorder struct {
	mock *MockCapabilityDetector
}

// NewMockCapabilityDetector creates a new mock instance.
func NewMockCapabilityDetector(ctrl *gomock.Controller) *MockCapabilityDetector {
	mock := &MockCapabilityDetector{ctrl: ctrl}
	mock.recorder = &MockCapabilityDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilityDetector) EXPECT() *MockCapabilityDetectorMockRecorder {
	return m.recorder
}

// ChooseStrategy mocks base method.
func (m *MockCapabilityDetector) ChooseStrategy(caps *capability.Capabilities) capability.StrategyType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChooseStrategy", caps)
	ret0, _ := ret[0].(capability.StrategyType)
	return ret0
}

// ChooseStrategy indicates an expected call of ChooseStrategy.
func (mr *MockCapabilityDetectorMockRecorder) ChooseStrategy(caps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChooseStrategy", reflect.TypeOf((*MockCapabilityDetector)(nil).ChooseStrategy), caps)
}

// Detect mocks base method.
func (m *MockCapabilityDetector) Detect(url string, auth transport.AuthMethod) (*capability.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", url, auth)
	ret0, _ := ret[0].(*capability.Capabilities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detect indicates an expected call of Detect.
func (mr *MockCapabilityDetectorMockRecorder) Detect(url, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockCapabilityDetector)(nil).Detect), url, auth)
}
