// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/fleet/internal/cmd/controller/reconciler (interfaces: TargetBuilder,Store)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=../../../mocks/reconciler_mock.go -package=mocks github.com/rancher/fleet/internal/cmd/controller/reconciler TargetBuilder,Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	target "github.com/rancher/fleet/internal/cmd/controller/target"
	manifest "github.com/rancher/fleet/internal/manifest"
	v1alpha1 "github.com/rancher/fleet/pkg/apis/fleet.cattle.io/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockTargetBuilder is a mock of TargetBuilder interface.
type MockTargetBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockTargetBuilderMockRecorder
	isgomock struct{}
}

// MockTargetBuilderMockRecorder is the mock recorder for MockTargetBuilder.
type MockTargetBuilderMockRecorder struct {
	mock *MockTargetBuilder
}

// NewMockTargetBuilder creates a new mock instance.
func NewMockTargetBuilder(ctrl *gomock.Controller) *MockTargetBuilder {
	mock := &MockTargetBuilder{ctrl: ctrl}
	mock.recorder = &MockTargetBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetBuilder) EXPECT() *MockTargetBuilderMockRecorder {
	return m.recorder
}

// Targets mocks base method.
func (m *MockTargetBuilder) Targets(ctx context.Context, bundle *v1alpha1.Bundle, manifestID string) ([]*target.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Targets", ctx, bundle, manifestID)
	ret0, _ := ret[0].([]*target.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Targets indicates an expected call of Targets.
func (mr *MockTargetBuilderMockRecorder) Targets(ctx, bundle, manifestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Targets", reflect.TypeOf((*MockTargetBuilder)(nil).Targets), ctx, bundle, manifestID)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockStore) Store(arg0 context.Context, arg1 *manifest.Manifest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockStoreMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockStore)(nil).Store), arg0, arg1)
}
