// Code generated by MockGen. DO NOT EDIT.
// Source: submodule.go
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -source=submodule.go -destination=../../../../mocks/submodule_updater_mock.go -package=mocks github.com/rancher/fleet/internal/cmd/cli/gitcloner/submodule SubmoduleFetcher,FetcherFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	strategy "github.com/rancher/fleet/internal/cmd/cli/gitcloner/submodule/strategy"
	gomock "go.uber.org/mock/gomock"
)

// MockSubmoduleFetcher is a mock of SubmoduleFetcher interface.
type MockSubmoduleFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockSubmoduleFetcherMockRecorder
	isgomock struct{}
}

// MockSubmoduleFetcherMockRecorder is the mock recorder for MockSubmoduleFetcher.
type MockSubmoduleFetcherMockRecorder struct {
	mock *MockSubmoduleFetcher
}

// NewMockSubmoduleFetcher creates a new mock instance.
func NewMockSubmoduleFetcher(ctrl *gomock.Controller) *MockSubmoduleFetcher {
	mock := &MockSubmoduleFetcher{ctrl: ctrl}
	mock.recorder = &MockSubmoduleFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmoduleFetcher) EXPECT() *MockSubmoduleFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockSubmoduleFetcher) Fetch(ctx context.Context, opt *strategy.FetchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, opt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSubmoduleFetcherMockRecorder) Fetch(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSubmoduleFetcher)(nil).Fetch), ctx, opt)
}
