// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/wrangler/v3/pkg/apply (interfaces: Apply)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./internal/mocks/wrangler_apply_mock.go -package=mocks github.com/rancher/wrangler/v3/pkg/apply Apply
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	apply "github.com/rancher/wrangler/v3/pkg/apply"
	injectors "github.com/rancher/wrangler/v3/pkg/apply/injectors"
	objectset "github.com/rancher/wrangler/v3/pkg/objectset"
	gomock "go.uber.org/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockApply is a mock of Apply interface.
type MockApply struct {
	ctrl     *gomock.Controller
	recorder *MockApplyMockRecorder
	isgomock struct{}
}

// MockApplyMockRecorder is the mock recorder for MockApply.
type MockApplyMockRecorder struct {
	mock *MockApply
}

// NewMockApply creates a new mock instance.
func NewMockApply(ctrl *gomock.Controller) *MockApply {
	mock := &MockApply{ctrl: ctrl}
	mock.recorder = &MockApplyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApply) EXPECT() *MockApplyMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockApply) Apply(set *objectset.ObjectSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", set)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockApplyMockRecorder) Apply(set any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockApply)(nil).Apply), set)
}

// ApplyObjects mocks base method.
func (m *MockApply) ApplyObjects(objs ...runtime.Object) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range objs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ApplyObjects", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyObjects indicates an expected call of ApplyObjects.
func (mr *MockApplyMockRecorder) ApplyObjects(objs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyObjects", reflect.TypeOf((*MockApply)(nil).ApplyObjects), objs...)
}

// DryRun mocks base method.
func (m *MockApply) DryRun(objs ...runtime.Object) (apply.Plan, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range objs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DryRun", varargs...)
	ret0, _ := ret[0].(apply.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DryRun indicates an expected call of DryRun.
func (mr *MockApplyMockRecorder) DryRun(objs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockApply)(nil).DryRun), objs...)
}

// FindOwner mocks base method.
func (m *MockApply) FindOwner(obj runtime.Object) (runtime.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOwner", obj)
	ret0, _ := ret[0].(runtime.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOwner indicates an expected call of FindOwner.
func (mr *MockApplyMockRecorder) FindOwner(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOwner", reflect.TypeOf((*MockApply)(nil).FindOwner), obj)
}

// PurgeOrphan mocks base method.
func (m *MockApply) PurgeOrphan(obj runtime.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeOrphan", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeOrphan indicates an expected call of PurgeOrphan.
func (mr *MockApplyMockRecorder) PurgeOrphan(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeOrphan", reflect.TypeOf((*MockApply)(nil).PurgeOrphan), obj)
}

// WithCacheTypeFactory mocks base method.
func (m *MockApply) WithCacheTypeFactory(factory apply.InformerFactory) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCacheTypeFactory", factory)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithCacheTypeFactory indicates an expected call of WithCacheTypeFactory.
func (mr *MockApplyMockRecorder) WithCacheTypeFactory(factory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCacheTypeFactory", reflect.TypeOf((*MockApply)(nil).WithCacheTypeFactory), factory)
}

// WithCacheTypes mocks base method.
func (m *MockApply) WithCacheTypes(igs ...apply.InformerGetter) apply.Apply {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range igs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithCacheTypes", varargs...)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithCacheTypes indicates an expected call of WithCacheTypes.
func (mr *MockApplyMockRecorder) WithCacheTypes(igs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCacheTypes", reflect.TypeOf((*MockApply)(nil).WithCacheTypes), igs...)
}

// WithContext mocks base method.
func (m *MockApply) WithContext(ctx context.Context) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockApplyMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockApply)(nil).WithContext), ctx)
}

// WithDefaultNamespace mocks base method.
func (m *MockApply) WithDefaultNamespace(ns string) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDefaultNamespace", ns)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithDefaultNamespace indicates an expected call of WithDefaultNamespace.
func (mr *MockApplyMockRecorder) WithDefaultNamespace(ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDefaultNamespace", reflect.TypeOf((*MockApply)(nil).WithDefaultNamespace), ns)
}

// WithDiffPatch mocks base method.
func (m *MockApply) WithDiffPatch(gvk schema.GroupVersionKind, namespace, name string, patch []byte) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDiffPatch", gvk, namespace, name, patch)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithDiffPatch indicates an expected call of WithDiffPatch.
func (mr *MockApplyMockRecorder) WithDiffPatch(gvk, namespace, name, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDiffPatch", reflect.TypeOf((*MockApply)(nil).WithDiffPatch), gvk, namespace, name, patch)
}

// WithDynamicLookup mocks base method.
func (m *MockApply) WithDynamicLookup() apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDynamicLookup")
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithDynamicLookup indicates an expected call of WithDynamicLookup.
func (mr *MockApplyMockRecorder) WithDynamicLookup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDynamicLookup", reflect.TypeOf((*MockApply)(nil).WithDynamicLookup))
}

// WithGVK mocks base method.
func (m *MockApply) WithGVK(gvks ...schema.GroupVersionKind) apply.Apply {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range gvks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithGVK", varargs...)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithGVK indicates an expected call of WithGVK.
func (mr *MockApplyMockRecorder) WithGVK(gvks ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithGVK", reflect.TypeOf((*MockApply)(nil).WithGVK), gvks...)
}

// WithIgnorePreviousApplied mocks base method.
func (m *MockApply) WithIgnorePreviousApplied() apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithIgnorePreviousApplied")
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithIgnorePreviousApplied indicates an expected call of WithIgnorePreviousApplied.
func (mr *MockApplyMockRecorder) WithIgnorePreviousApplied() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithIgnorePreviousApplied", reflect.TypeOf((*MockApply)(nil).WithIgnorePreviousApplied))
}

// WithInjector mocks base method.
func (m *MockApply) WithInjector(injs ...injectors.ConfigInjector) apply.Apply {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range injs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithInjector", varargs...)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithInjector indicates an expected call of WithInjector.
func (mr *MockApplyMockRecorder) WithInjector(injs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInjector", reflect.TypeOf((*MockApply)(nil).WithInjector), injs...)
}

// WithInjectorName mocks base method.
func (m *MockApply) WithInjectorName(injs ...string) apply.Apply {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range injs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithInjectorName", varargs...)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithInjectorName indicates an expected call of WithInjectorName.
func (mr *MockApplyMockRecorder) WithInjectorName(injs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInjectorName", reflect.TypeOf((*MockApply)(nil).WithInjectorName), injs...)
}

// WithListerNamespace mocks base method.
func (m *MockApply) WithListerNamespace(ns string) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithListerNamespace", ns)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithListerNamespace indicates an expected call of WithListerNamespace.
func (mr *MockApplyMockRecorder) WithListerNamespace(ns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithListerNamespace", reflect.TypeOf((*MockApply)(nil).WithListerNamespace), ns)
}

// WithNoDelete mocks base method.
func (m *MockApply) WithNoDelete() apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithNoDelete")
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithNoDelete indicates an expected call of WithNoDelete.
func (mr *MockApplyMockRecorder) WithNoDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithNoDelete", reflect.TypeOf((*MockApply)(nil).WithNoDelete))
}

// WithNoDeleteGVK mocks base method.
func (m *MockApply) WithNoDeleteGVK(gvks ...schema.GroupVersionKind) apply.Apply {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range gvks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WithNoDeleteGVK", varargs...)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithNoDeleteGVK indicates an expected call of WithNoDeleteGVK.
func (mr *MockApplyMockRecorder) WithNoDeleteGVK(gvks ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithNoDeleteGVK", reflect.TypeOf((*MockApply)(nil).WithNoDeleteGVK), gvks...)
}

// WithOwner mocks base method.
func (m *MockApply) WithOwner(obj runtime.Object) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithOwner", obj)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithOwner indicates an expected call of WithOwner.
func (mr *MockApplyMockRecorder) WithOwner(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithOwner", reflect.TypeOf((*MockApply)(nil).WithOwner), obj)
}

// WithOwnerKey mocks base method.
func (m *MockApply) WithOwnerKey(key string, gvk schema.GroupVersionKind) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithOwnerKey", key, gvk)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithOwnerKey indicates an expected call of WithOwnerKey.
func (mr *MockApplyMockRecorder) WithOwnerKey(key, gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithOwnerKey", reflect.TypeOf((*MockApply)(nil).WithOwnerKey), key, gvk)
}

// WithPatcher mocks base method.
func (m *MockApply) WithPatcher(gvk schema.GroupVersionKind, patchers apply.Patcher) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPatcher", gvk, patchers)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithPatcher indicates an expected call of WithPatcher.
func (mr *MockApplyMockRecorder) WithPatcher(gvk, patchers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPatcher", reflect.TypeOf((*MockApply)(nil).WithPatcher), gvk, patchers)
}

// WithRateLimiting mocks base method.
func (m *MockApply) WithRateLimiting(ratelimitingQps float32) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithRateLimiting", ratelimitingQps)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithRateLimiting indicates an expected call of WithRateLimiting.
func (mr *MockApplyMockRecorder) WithRateLimiting(ratelimitingQps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithRateLimiting", reflect.TypeOf((*MockApply)(nil).WithRateLimiting), ratelimitingQps)
}

// WithReconciler mocks base method.
func (m *MockApply) WithReconciler(gvk schema.GroupVersionKind, reconciler apply.Reconciler) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithReconciler", gvk, reconciler)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithReconciler indicates an expected call of WithReconciler.
func (mr *MockApplyMockRecorder) WithReconciler(gvk, reconciler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithReconciler", reflect.TypeOf((*MockApply)(nil).WithReconciler), gvk, reconciler)
}

// WithRestrictClusterScoped mocks base method.
func (m *MockApply) WithRestrictClusterScoped() apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithRestrictClusterScoped")
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithRestrictClusterScoped indicates an expected call of WithRestrictClusterScoped.
func (mr *MockApplyMockRecorder) WithRestrictClusterScoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithRestrictClusterScoped", reflect.TypeOf((*MockApply)(nil).WithRestrictClusterScoped))
}

// WithSetID mocks base method.
func (m *MockApply) WithSetID(id string) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSetID", id)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithSetID indicates an expected call of WithSetID.
func (mr *MockApplyMockRecorder) WithSetID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSetID", reflect.TypeOf((*MockApply)(nil).WithSetID), id)
}

// WithSetOwnerReference mocks base method.
func (m *MockApply) WithSetOwnerReference(controller, block bool) apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSetOwnerReference", controller, block)
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithSetOwnerReference indicates an expected call of WithSetOwnerReference.
func (mr *MockApplyMockRecorder) WithSetOwnerReference(controller, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSetOwnerReference", reflect.TypeOf((*MockApply)(nil).WithSetOwnerReference), controller, block)
}

// WithStrictCaching mocks base method.
func (m *MockApply) WithStrictCaching() apply.Apply {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStrictCaching")
	ret0, _ := ret[0].(apply.Apply)
	return ret0
}

// WithStrictCaching indicates an expected call of WithStrictCaching.
func (mr *MockApplyMockRecorder) WithStrictCaching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStrictCaching", reflect.TypeOf((*MockApply)(nil).WithStrictCaching))
}
