// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/wrangler/v3/pkg/generated/controllers/core/v1 (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/wrangler_core_mock.go -package=mocks -mock_names=Interface=MockWranglerCore github.com/rancher/wrangler/v3/pkg/generated/controllers/core/v1 Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1 "github.com/rancher/wrangler/v3/pkg/generated/controllers/core/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockWranglerCore is a mock of Interface interface.
type MockWranglerCore struct {
	ctrl     *gomock.Controller
	recorder *MockWranglerCoreMockRecorder
	isgomock struct{}
}

// MockWranglerCoreMockRecorder is the mock recorder for MockWranglerCore.
type MockWranglerCoreMockRecorder struct {
	mock *MockWranglerCore
}

// NewMockWranglerCore creates a new mock instance.
func NewMockWranglerCore(ctrl *gomock.Controller) *MockWranglerCore {
	mock := &MockWranglerCore{ctrl: ctrl}
	mock.recorder = &MockWranglerCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWranglerCore) EXPECT() *MockWranglerCoreMockRecorder {
	return m.recorder
}

// ConfigMap mocks base method.
func (m *MockWranglerCore) ConfigMap() v1.ConfigMapController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigMap")
	ret0, _ := ret[0].(v1.ConfigMapController)
	return ret0
}

// ConfigMap indicates an expected call of ConfigMap.
func (mr *MockWranglerCoreMockRecorder) ConfigMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigMap", reflect.TypeOf((*MockWranglerCore)(nil).ConfigMap))
}

// Endpoints mocks base method.
func (m *MockWranglerCore) Endpoints() v1.EndpointsController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoints")
	ret0, _ := ret[0].(v1.EndpointsController)
	return ret0
}

// Endpoints indicates an expected call of Endpoints.
func (mr *MockWranglerCoreMockRecorder) Endpoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoints", reflect.TypeOf((*MockWranglerCore)(nil).Endpoints))
}

// Event mocks base method.
func (m *MockWranglerCore) Event() v1.EventController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event")
	ret0, _ := ret[0].(v1.EventController)
	return ret0
}

// Event indicates an expected call of Event.
func (mr *MockWranglerCoreMockRecorder) Event() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockWranglerCore)(nil).Event))
}

// LimitRange mocks base method.
func (m *MockWranglerCore) LimitRange() v1.LimitRangeController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LimitRange")
	ret0, _ := ret[0].(v1.LimitRangeController)
	return ret0
}

// LimitRange indicates an expected call of LimitRange.
func (mr *MockWranglerCoreMockRecorder) LimitRange() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LimitRange", reflect.TypeOf((*MockWranglerCore)(nil).LimitRange))
}

// Namespace mocks base method.
func (m *MockWranglerCore) Namespace() v1.NamespaceController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace")
	ret0, _ := ret[0].(v1.NamespaceController)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockWranglerCoreMockRecorder) Namespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockWranglerCore)(nil).Namespace))
}

// Node mocks base method.
func (m *MockWranglerCore) Node() v1.NodeController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(v1.NodeController)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockWranglerCoreMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockWranglerCore)(nil).Node))
}

// PersistentVolume mocks base method.
func (m *MockWranglerCore) PersistentVolume() v1.PersistentVolumeController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistentVolume")
	ret0, _ := ret[0].(v1.PersistentVolumeController)
	return ret0
}

// PersistentVolume indicates an expected call of PersistentVolume.
func (mr *MockWranglerCoreMockRecorder) PersistentVolume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistentVolume", reflect.TypeOf((*MockWranglerCore)(nil).PersistentVolume))
}

// PersistentVolumeClaim mocks base method.
func (m *MockWranglerCore) PersistentVolumeClaim() v1.PersistentVolumeClaimController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistentVolumeClaim")
	ret0, _ := ret[0].(v1.PersistentVolumeClaimController)
	return ret0
}

// PersistentVolumeClaim indicates an expected call of PersistentVolumeClaim.
func (mr *MockWranglerCoreMockRecorder) PersistentVolumeClaim() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistentVolumeClaim", reflect.TypeOf((*MockWranglerCore)(nil).PersistentVolumeClaim))
}

// Pod mocks base method.
func (m *MockWranglerCore) Pod() v1.PodController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pod")
	ret0, _ := ret[0].(v1.PodController)
	return ret0
}

// Pod indicates an expected call of Pod.
func (mr *MockWranglerCoreMockRecorder) Pod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pod", reflect.TypeOf((*MockWranglerCore)(nil).Pod))
}

// ResourceQuota mocks base method.
func (m *MockWranglerCore) ResourceQuota() v1.ResourceQuotaController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceQuota")
	ret0, _ := ret[0].(v1.ResourceQuotaController)
	return ret0
}

// ResourceQuota indicates an expected call of ResourceQuota.
func (mr *MockWranglerCoreMockRecorder) ResourceQuota() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceQuota", reflect.TypeOf((*MockWranglerCore)(nil).ResourceQuota))
}

// Secret mocks base method.
func (m *MockWranglerCore) Secret() v1.SecretController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secret")
	ret0, _ := ret[0].(v1.SecretController)
	return ret0
}

// Secret indicates an expected call of Secret.
func (mr *MockWranglerCoreMockRecorder) Secret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secret", reflect.TypeOf((*MockWranglerCore)(nil).Secret))
}

// Service mocks base method.
func (m *MockWranglerCore) Service() v1.ServiceController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service")
	ret0, _ := ret[0].(v1.ServiceController)
	return ret0
}

// Service indicates an expected call of Service.
func (mr *MockWranglerCoreMockRecorder) Service() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockWranglerCore)(nil).Service))
}

// ServiceAccount mocks base method.
func (m *MockWranglerCore) ServiceAccount() v1.ServiceAccountController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAccount")
	ret0, _ := ret[0].(v1.ServiceAccountController)
	return ret0
}

// ServiceAccount indicates an expected call of ServiceAccount.
func (mr *MockWranglerCoreMockRecorder) ServiceAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAccount", reflect.TypeOf((*MockWranglerCore)(nil).ServiceAccount))
}
