apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: {{.Name}}
  namespace: "fleet-local"
spec:
  helm:
    releaseName: testhelm
    repo: {{.Repo}}
    chart: {{.Chart}}
    version: '{{.Version}}'
  pollingInterval: {{.PollingInterval}}
  namespace: {{.Namespace}}
  helmSecretName: {{.HelmSecretName}}
  insecureSkipTLSVerify: {{.InsecureSkipTLSVerify}}
