apiVersion: v2
name: fleet-simulator
description: Fleet Manager Agent Simulator - GitOps at Scale
version: 0.0.0
appVersion: 0.0.0
icon: https://charts.rancher.io/assets/logos/fleet.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: fleet-simulator-system
  catalog.cattle.io/release-name: fleet-simulator
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows

