kind: ConfigMap
apiVersion: v1
metadata:
  name: fleet-agent
data:
  config: |-
    {
      {{ if .Values.labels }}
      "labels":{{toJson .Values.labels}},
      {{ end }}
      "clientID":"{{.Values.clientID}}",
      {{ if .Values.garbageCollectionInterval }}
      "garbageCollectionInterval": "{{.Values.garbageCollectionInterval}}",
      {{ end }}
      "agentTLSMode": "{{.Values.agentTLSMode}}"
    }
