kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: imagescan
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: {{.Repo}}
  branch: {{.Branch}}
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5s
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
  paths:
  - examples
