#!/bin/bash
#
# Submit new Fleet version against rancher/charts

set -uex

PREV_FLEET_VERSION=$1   # e.g. 0.5.2-rc.3
NEW_FLEET_VERSION=$2
PREV_CHART_VERSION=$3   # e.g. 101.2.0
NEW_CHART_VERSION=$4
REPLACE=$5              # remove previous version if `true`, otherwise add new

if [ -z "${GITHUB_WORKSPACE:-}" ]; then
    CHARTS_DIR="$(dirname -- "$0")/../../../charts"
else
    CHARTS_DIR="${GITHUB_WORKSPACE}/charts"
fi

pushd "${CHARTS_DIR}" > /dev/null

if [ ! -e ~/.gitconfig ]; then
    git config --global user.name "fleet-bot"
    git config --global user.email fleet@suse.de
fi

if [ ! -f bin/charts-build-scripts ]; then
    make pull-scripts
fi

find ./packages/fleet/ -type f -exec sed -i -e "s/${PREV_FLEET_VERSION}/${NEW_FLEET_VERSION}/g" {} \;
find ./packages/fleet/ -type f -exec sed -i -e "s/version: ${PREV_CHART_VERSION}/version: ${NEW_CHART_VERSION}/g" {} \;

if [ "${REPLACE}" == "true" ]; then
    sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}/${NEW_CHART_VERSION}+up${NEW_FLEET_VERSION}/g" release.yaml
else
    sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}/${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}\n${NEW_CHART_VERSION}+up${NEW_FLEET_VERSION}/g" release.yaml
    if grep -qv "fleet:" release.yaml; then

        cat <<< "fleet:
- ${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_FLEET_VERSION}
fleet-agent:
- ${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_FLEET_VERSION}
fleet-crd:
- ${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_FLEET_VERSION}" >> release.yaml

    fi
fi

git add packages/fleet release.yaml
git commit -m "Updating to Fleet v${NEW_FLEET_VERSION}"

if [ "${REPLACE}" == "true" ]; then
for i in fleet fleet-crd fleet-agent; do CHART=$i VERSION=${PREV_CHART_VERSION}+up${PREV_FLEET_VERSION} make remove; done
fi

PACKAGE=fleet make charts
git add assets/fleet* charts/fleet* index.yaml
git commit -m "Autogenerated changes for Fleet v${NEW_FLEET_VERSION}"

popd > /dev/null