---

kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64
steps:
- name: build
  image: rancher/dapper:v0.5.8
  environment:
    CROSS: "windows"
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: fossa
  image: registry.suse.com/suse/sle15:15.3
  failure: ignore
  environment:
    FOSSA_API_KEY:
      from_secret: FOSSA_API_KEY
  commands:
    - zypper -n install curl unzip
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"
    - fossa analyze
    - fossa test
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - push
      - tag
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: upload-tag
  pull: default
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: ./dist/artifacts
    target: releases.rancher.com/fleet/${DRONE_TAG}
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
- name: upload-latest
  pull: default
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: ./dist/artifacts
    target: releases.rancher.com/fleet/latest
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=amd64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=amd64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: linux-arm64
platform:
  os: linux
  arch: arm64
steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: windows-1809
platform:
  os: windows
  arch: amd64
  version: 1809
# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20
steps:
- name: docker-publish-agent
  image: plugins/docker:windows-1809-amd64
  settings:
    purge: false
    dockerfile: package/Dockerfile-windows.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-windows-1809"
    username:
      from_secret: docker_username
    build_args:
      - "SERVERCORE_VERSION=1809"
      - "RELEASES=releases.rancher.com"
      - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
  volumes:
    - name: docker
      path: \\\\.\\pipe\\docker_engine
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
  - name: docker
    host:
      path: \\\\.\\pipe\\docker_engine
depends_on:
- linux-amd64

---

kind: pipeline
type: docker
name: windows-2022
platform:
  os: windows
  arch: amd64
  version: 2022
# Currently have to define "depth" as otherwise clone fails at
# https://github.com/drone/drone-git/blob/39d233b3d9eccc68e66508a06a725a2567f33143/windows/clone-tag.ps1#L12
clone:
  depth: 20
steps:
  - name: docker-publish-agent
    image: rancher/drone-images:docker-amd64-ltsc2022
    settings:
      dockerfile: package/Dockerfile-windows.agent
      password:
        from_secret: docker_password
      repo: "rancher/fleet-agent"
      tag: "${DRONE_TAG}-windows-ltsc2022"
      username:
        from_secret: docker_username
      build_args:
        - "SERVERCORE_VERSION=ltsc2022"
        - "RELEASES=releases.rancher.com"
        - "VERSION=${DRONE_TAG}"
        - ARCH=amd64
      context: package/
      custom_dns: 1.1.1.1
    volumes:
      - name: docker
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: \\\\.\\pipe\\docker_engine
depends_on:
  - linux-amd64

---

kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: manifest-agent
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest-agent.tmpl
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
depends_on:
- linux-amd64
- linux-arm64
- windows-1809
- windows-2022
