---

kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64
steps:
- name: build
  image: rancher/dapper:v0.5.8
  environment:
    CROSS: "windows"
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: fossa
  image: registry.suse.com/suse/sle15:15.3
  failure: ignore
  environment:
    FOSSA_API_KEY:
      from_secret: FOSSA_API_KEY
  commands:
    - zypper -n install curl unzip
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | sh"
    - fossa analyze
    - fossa test
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - push
      - tag
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: upload-tag
  pull: default
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: ./dist/artifacts
    target: releases.rancher.com/fleet/${DRONE_TAG}
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
- name: upload-latest
  pull: default
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: ./dist/artifacts
    target: releases.rancher.com/fleet/latest
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=amd64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=amd64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: linux-arm64
platform:
  os: linux
  arch: arm64
steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-arm64"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm64"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: linux-s390x
platform:
  os: linux
  arch: amd64
# Hack needed for s390x: https://gist.github.com/colstrom/c2f359f72658aaabb44150ac20b16d7c#gistcomment-3858388
node:
  arch: s390x
steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: github_binary_release
  image: rancher/drone-images:github-release-s390x
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-s390x.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish-agent
  image: rancher/drone-images:docker-s390x
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-s390x"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=s390x"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: rancher/drone-images:docker-s390x
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-s390x"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=s390x"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: linux-arm
platform:
  os: linux
  arch: arm
steps:
# Update this tag once dapper arm v7 works on drone.
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper build
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-linux-arm"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/fleet"
    tag: "${DRONE_TAG}-linux-arm"
    username:
      from_secret: docker_username
    build_args:
      - "ARCH=arm"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: windows-1809
platform:
  os: windows
  arch: amd64
  version: 1809
steps:
- name: docker-publish-agent
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile-windows.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-windows-1809"
    username:
      from_secret: docker_username
    build_args:
      - "SERVERCORE_VERSION=1809"
      - "RELEASES=releases.rancher.com"
      - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
  volumes:
    - name: docker
      path: \\\\.\\pipe\\docker_engine
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
  - name: docker
    host:
      path: \\\\.\\pipe\\docker_engine
depends_on:
- linux-amd64

---
kind: pipeline
type: docker
name: windows-20H2
platform:
  os: windows
  arch: amd64
  version: 20H2
# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true
steps:
- name: clone
  image: rancher/drone-images:git-20H2
  settings:
    depth: 1
- name: docker-publish-agent
  image: rancher/drone-images:docker-20H2
  settings:
    dockerfile: package/Dockerfile-windows.agent
    password:
      from_secret: docker_password
    repo: "rancher/fleet-agent"
    tag: "${DRONE_TAG}-windows-20H2"
    username:
      from_secret: docker_username
    build_args:
      - "SERVERCORE_VERSION=20H2"
      - "RELEASES=releases.rancher.com"
      - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
  volumes:
    - name: docker
      path: \\\\.\\pipe\\docker_engine
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
  - name: docker
    host:
      path: \\\\.\\pipe\\docker_engine
depends_on:
- linux-amd64

---

kind: pipeline
type: docker
name: windows-2022
platform:
  os: windows
  arch: amd64
  version: 2022
# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true
steps:
  - name: clone
    image: rancher/drone-images:git-amd64-ltsc2022
    settings:
      depth: 1
  - name: docker-publish-agent
    image: rancher/drone-images:docker-amd64-ltsc2022
    settings:
      dockerfile: package/Dockerfile-windows.agent
      password:
        from_secret: docker_password
      repo: "rancher/fleet-agent"
      tag: "${DRONE_TAG}-windows-ltsc2022"
      username:
        from_secret: docker_username
      build_args:
        - "SERVERCORE_VERSION=ltsc2022"
        - "RELEASES=releases.rancher.com"
        - "VERSION=${DRONE_TAG}"
      context: package/
      custom_dns: 1.1.1.1
    volumes:
      - name: docker
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: \\\\.\\pipe\\docker_engine
depends_on:
  - linux-amd64

---

kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: manifest-agent
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest-agent.tmpl
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
depends_on:
- linux-amd64
- linux-arm64
- linux-arm
- windows-1809
- windows-20H2
- windows-2022
- linux-s390x
