---
version: 2

project_name: fleet
release:
  prerelease: auto
  disable: "{{ .Env.IS_HOTFIX }}"

before:
  hooks:
    - go mod download

archives:
  - id: fleet-controller
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-controller

  - id: fleet-agent
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-agent

  - id: fleet-cli
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - fleet-cli

builds:
  -
    id: fleet-controller
    main: ./cmd/fleetcontroller
    binary: fleetcontroller-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    # gcflags:
    #   - all="-N -l"
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_amd64_v1
    - linux_arm64
  -
    id: fleet-agent
    main: ./cmd/fleetagent
    binary: fleetagent-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_amd64_v1
    - linux_arm64
    - windows_amd64
  -
    id: fleet-cli
    main: ./cmd/fleetcli
    binary: fleet-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_amd64_v1
    - linux_arm64
    - windows_amd64

changelog:
  disable: false
  use: github-native

env:
  - CGO_ENABLED=0
  - IS_HOTFIX={{ if isEnvSet "IS_HOTFIX"}}{{ .Env.IS_HOTFIX }}{{else}}false{{end}}
  - REGISTRY={{ if isEnvSet "REGISTRY" }}{{ .Env.REGISTRY }}{{else}}docker.io{{end}}

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  # fleet-controller images
  -
    use: buildx

    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # IDs to filter the binaries/packages.
    ids:
    - fleet-controller
    - fleet-cli

    # Templates of the Docker image names.
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet:{{ .Tag }}-linux-amd64"

    # Path to the Dockerfile (from the project root).
    dockerfile: package/Dockerfile

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
    - "--build-arg=ARCH=amd64"
    - "--build-arg=BUILD_ENV=goreleaser"
    - "--platform=linux/amd64"
    extra_files: [ "package/log.sh" ]
  -
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - fleet-controller
    - fleet-cli
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet:{{ .Tag }}-linux-arm64"
    dockerfile: package/Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
    - "--build-arg=ARCH=arm64"
    - "--build-arg=BUILD_ENV=goreleaser"
    - "--platform=linux/arm64/v8"
    extra_files: [ "package/log.sh" ]
  # fleet-agent images
  -
    use: buildx
    goos: linux
    goarch: amd64
    ids:
    - fleet-agent
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet-agent:{{ .Tag }}-linux-amd64"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
    - "--build-arg=ARCH=amd64"
    - "--build-arg=BUILD_ENV=goreleaser"
    - "--platform=linux/amd64"
  -
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - fleet-agent
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet-agent:{{ .Tag }}-linux-arm64"
    dockerfile: package/Dockerfile.agent
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/rancher/fleet"
    - "--build-arg=ARCH=arm64"
    - "--build-arg=BUILD_ENV=goreleaser"
    - "--platform=linux/arm64/v8"

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: "{{ .Env.REGISTRY }}/rancher/fleet:{{ .Tag }}"
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet:{{ .Tag }}-linux-amd64"
    - "{{ .Env.REGISTRY }}/rancher/fleet:{{ .Tag }}-linux-arm64"

  - name_template: "{{ .Env.REGISTRY }}/rancher/fleet-agent:{{ .Tag }}"
    image_templates:
    - "{{ .Env.REGISTRY }}/rancher/fleet-agent:{{ .Tag }}-linux-amd64"
    - "{{ .Env.REGISTRY }}/rancher/fleet-agent:{{ .Tag }}-linux-arm64"
