---
version: 2

project_name: fleet

env:
  - CGO_ENABLED=0
  - IS_HOTFIX={{ if isEnvSet "IS_HOTFIX"}}{{ .Env.IS_HOTFIX }}{{else}}false{{end}}

release:
  prerelease: auto
  disable: "{{ .Env.IS_HOTFIX }}"

changelog:
  disable: false
  use: github-native

before:
  hooks:
    - go mod download

archives:
  - id: fleet-controller
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-controller

  - id: fleet-agent
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-agent

  - id: fleet-cli
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-cli

  - id: fleet-benchmark
    formats: [ "binary" ]
    name_template: "{{ .Binary }}"
    ids:
      - fleet-benchmark

builds:
  -
    id: fleet-controller
    main: ./cmd/fleetcontroller
    binary: fleetcontroller-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    # gcflags:
    #   - all="-N -l"
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_amd64_v1
    - linux_arm64
  -
    id: fleet-agent
    main: ./cmd/fleetagent
    binary: fleetagent-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - linux_amd64_v1
    - linux_arm64
    - windows_amd64
  -
    id: fleet-cli
    main: ./cmd/fleetcli
    binary: fleet-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - darwin_arm64
    - linux_amd64_v1
    - linux_arm64
    - windows_amd64
  -
    id: fleet-benchmark
    main: ./benchmarks/cmd
    binary: fleet-benchmark-{{ .Os }}-{{ .Arch }}{{ if .Arm }}64{{ end }}
    no_unique_dist_dir: true
    ldflags:
      - -w -s
      - -X github.com/rancher/fleet/pkg/version.GitCommit={{ .Commit }}
      - -X github.com/rancher/fleet/pkg/version.Version={{ .Tag }}
    targets:
    - darwin_arm64
    - linux_amd64_v1
    - linux_arm64
    - windows_amd64

snapshot:
  version_template: "{{ .Tag }}-next"

dockers_v2:
  # Public fleet-controller images
  -
    id: fleet-public
    disable: "{{ .Env.IS_HOTFIX }}"
    ids:
    - fleet-controller
    - fleet-cli
    images:
    - "docker.io/rancher/fleet"
    tags:
    - "{{ .Tag }}"
    dockerfile: package/Dockerfile
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/rancher/fleet"
    build_args:
      ARCH: "{{ .Arch }}"
      BUILD_ENV: "goreleaser"
    flags:
    - "--pull"
    extra_files: [ "package/log.sh" ]
    platforms:
    - linux/amd64
    - linux/arm64/v8

  # Public fleet-agent images
  -
    id: fleet-agent-public
    disable: "{{ .Env.IS_HOTFIX }}"
    ids:
    - fleet-agent
    images:
    - "docker.io/rancher/fleet-agent"
    tags:
    - "{{ .Tag }}"
    dockerfile: package/Dockerfile.agent
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/rancher/fleet"
    build_args:
      ARCH: "{{ .Arch }}"
      BUILD_ENV: "goreleaser"
    flags:
    - "--pull"
    platforms:
    - linux/amd64
    - linux/arm64/v8

  # Staging fleet-controller images with provenance
  -
    id: fleet-private
    ids:
    - fleet-controller
    - fleet-cli
    images:
    - "{{ .Env.STAGE_REGISTRY }}/rancher/fleet"
    tags:
    - "{{ .Tag }}"
    dockerfile: package/Dockerfile
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/rancher/fleet"
    build_args:
      ARCH: "{{ .Arch }}"
      BUILD_ENV: "goreleaser"
    flags:
    - "--pull"
    - "--sbom=true"
    - "--provenance=true"
    - "--provenance=mode=max"
    extra_files: [ "package/log.sh" ]
    platforms:
    - linux/amd64
    - linux/arm64/v8

  # Staging fleet-agent images with provenance
  -
    id: fleet-agent-private
    ids:
    - fleet-agent
    images:
    - "{{ .Env.STAGE_REGISTRY }}/rancher/fleet-agent"
    tags:
    - "{{ .Tag }}"
    dockerfile: package/Dockerfile.agent
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/rancher/fleet"
    build_args:
      ARCH: "{{ .Arch }}"
      BUILD_ENV: "goreleaser"
    flags:
    - "--pull"
    - "--sbom=true"
    - "--provenance=true"
    - "--provenance=mode=max"
    platforms:
    - linux/amd64
    - linux/arm64/v8

docker_digest:
  name_template: "digests.txt"

docker_signs:
  - id: prime-fleet
    cmd: cosign
    args:
      - "sign"
      - "--oidc-provider=github-actions"
      - "--yes"
      - "--sign-container-identity={{ .Env.PRIME_REGISTRY }}/rancher/fleet"
      - "${artifact}@${digest}"
    artifacts: all
    ids:
      - fleet-private

  - id: prime-fleet-agent
    cmd: cosign
    args:
      - "sign"
      - "--oidc-provider=github-actions"
      - "--yes"
      - "--sign-container-identity={{ .Env.PRIME_REGISTRY }}/rancher/fleet-agent"
      - "${artifact}@${digest}"
    artifacts: all
    ids:
      - fleet-agent-private