[files]
extend-exclude = [
  "go.mod",
  "go.sum",
  "ssh_host_ecdsa_key",
  "cloner_test.go",
  "netutils_test.go",
  "pkg/apis/internal/scheme.go",
]

[default.extend-identifiers]
"passin" = "passin"
"ANDed" = "ANDed"
"HoTWPQxTJ5dIY31" = "HoTWPQxTJ5dIY31"
"wre" = "wre" # warning regular expression, not 'were'
