[files]
extend-exclude = [
  "go.mod",
  "go.sum",
  "ssh_host_ecdsa_key",
  "cloner_test.go",
  "netutils_test.go",
  "pkg/apis/internal/scheme.go",
]

[default.extend-identifiers]
"passin" = "passin"
"ANDed" = "ANDed"
"HoTWPQxTJ5dIY31" = "HoTWPQxTJ5dIY31"
"wre" = "wre"                         # warning regular expression, not 'were'

[default]
extend-ignore-re = [
    "-{5}BEGIN RSA PRIVATE KEY-{5}(?:$|[^-]{63,}-{5}END)",
    "-{5}BEGIN PRIVATE KEY-{5}(?:$|[^-]{63,}-{5}END)",
]
