#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

if [ -n "${DEBUG}" ]; then
  GCFLAGS="-N -l"
fi

if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static"
    if [ -z "${DEBUG}" ]; then
      OTHER_LINKFLAGS="${OTHER_LINKFLAGS} -s"
    fi
fi

CGO_ENABLED=0 go build -gcflags="all=${GCFLAGS}" -ldflags "$OTHER_LINKFLAGS" -o bin/gitjob
CGO_ENABLED=0 go build -gcflags="all=${GCFLAGS}" -ldflags "$OTHER_LINKFLAGS" -o bin/gitcloner ./cmd/gitcloner

if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -gcflags="all=${GCFLAGS}" -o bin/gitjob-darwin
    GOOS=windows go build -gcflags="all=${GCFLAGS}" -o bin/gitjob-windows
    GOOS=darwin go build -gcflags="all=${GCFLAGS}" -o bin/gitcloner-darwin ./cmd/gitcloner
    GOOS=windows go build -gcflags="all=${GCFLAGS}" -o bin/gitcloner-windows ./cmd/gitcloner
fi
