#!/bin/bash
set -e

if ! hash helm 2>/dev/null; then
    exit 0
fi

cd $(dirname $0)/..
. ./scripts/version

rm -rf build/chart
mkdir -p build dist/artifacts
cp -rf chart build/
rm -rf build/chart/crds

sed -i \
    -e 's/version:.*/version: '${HELM_VERSION}'/' \
    -e 's/appVersion:.*/appVersion: '${HELM_VERSION}'/' \
    build/chart/Chart.yaml

sed -i \
    -e 's/tag:.*/tag: '${HELM_TAG}'/' \
    build/chart/values.yaml

mkdir build/chart/crds
go run pkg/crdgen/main.go > ./build/chart/crds/crds.yaml
helm package -d ./dist/artifacts ./build/chart
