kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test-simple
spec:
  repo: https://github.com/rancher/fleet-examples
  branch: test-simple
  paths:
    - simple-chart
    - simple-manifest
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
