#!/usr/bin/env bash

export DEFAULT_CONFIG="dev/env.multi-cluster-defaults"
export CUSTOM_CONFIG_FILE="env.multi-cluster"

# shellcheck source=dev/setup-cluster-config
source dev/setup-cluster-config

FLEET_E2E_DS_CLUSTER_COUNT=${FLEET_E2E_DS_CLUSTER_COUNT:-1}

# Cleans with settings sourced, so it should be rather selective.
./dev/k3d-clean

PORT_OFFSET=0
if [ -z "$external_ip" ];
then
 PORT_OFFSET=$(( RANDOM % 10001 ))
fi

./dev/setup-k3d "${FLEET_E2E_CLUSTER#k3d-}" "$PORT_OFFSET"
./dev/setup-k3ds-downstream
./dev/build-fleet
./dev/import-images-k3d
./dev/setup-fleet-multi-cluster

# needed for gitrepo tests
./dev/import-images-tests-k3d
./dev/create-zot-certs 'FleetCI-RootCA' # for OCI tests
./e2e/testenv/infra/infra setup
