apiVersion: v1
kind: Secret
metadata:
  name: zot-htpasswd
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "zot"
      #meta.helm.sh/release-namespace: "default"
stringData:
  htpasswd: "{{.HTTPPasswd}}"
