kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: dont-keep
spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - helm-verify
  targetNamespace: do-not-keep-resources
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
