---
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  labels:
    role: root
  name: {{.Name}}
  namespace: {{.ClusterRegistrationNamespace}}
spec:
  defaultNamespace: {{.ProjectNamespace}}
  resources:
  - content: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: root
      data:
        value: root
    name: cm.yaml
  targets:
  - clusterSelector: {}
