---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.ProjectNamespace}}
{{if .Restricted}}
---
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: {{.ProjectNamespace}}

allowedTargetNamespaces:
  - project1simpleapp
{{end}}
---
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: {{.ProjectNamespace}}

bundleSelector:
  matchLabels:
    team: {{ .BundleSelectorLabel }}

namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: {{.ClusterNamespace}}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapp
  namespace: {{.ProjectNamespace}}
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - simple

  {{.TargetNamespace}}

  targets:
  - name: test
    clusterSelector:
      matchLabels:
        env: test
