apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjob
spec:
  selector:
    matchLabels:
      app: "gitjob"
  template:
    metadata:
      labels:
        app: "gitjob"
    spec:
      serviceAccountName: gitjob
      containers:
        - image: "{{ template "system_default_registry" . }}{{ .Values.gitjob.repository }}:{{ .Values.gitjob.tag }}"
          name: gitjob
          command:
          - gitjob
          {{- if .Values.debug }}
          - --debug
          {{- end }}
          - --tekton-image
          - "{{ template "system_default_registry" . }}{{ .Values.tekton.repository }}:{{ .Values.tekton.tag }}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.proxy }}
            - name: HTTP_PROXY
              value: {{ .Values.proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.proxy }}
            - name: NO_PROXY
              value: {{ .Values.noProxy }}
          {{- end }}
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
