kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{ .Name }}

spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: {{ .Branch }}
  paths:
    {{- range .Paths}}
    - {{.}}
    {{- end}}

  targetNamespace: {{ .TargetNamespace }}
