name: Integration tests

on:
  pull_request:
  push:
    branches:
    - 'master'

env:
  GOARCH: amd64
  CGO_ENABLED: 0

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: gitjob integration-test
        run: go test -v ./integrationtests/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          
      - name: git cloner integration-test
        run: go test -v ./cmd/gitcloner/integrationtests/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
