name: Integration tests

on:
  pull_request:
  push:
    branches:
    - 'master'

env:
  GOARCH: amd64
  CGO_ENABLED: 0

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: gitjob integration-test
        env:
          SETUP_ENVTEST_VER: v0.0.0-20221214170741-69f093833822
          ENVTEST_K8S_VERSION: 1.25
          TESTCONTAINERS_RYUK_DISABLED: true
        run: ./.github/scripts/run-integration-tests.sh

      - name: git cloner integration-test
        run: go test -v ./cmd/gitcloner/integrationtests/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
