apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller

{{- if .Values.bootstrap.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-controller-bootstrap
{{- end }}
