kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{.Name}}
spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - simple
  targetNamespace: {{.TargetNamespace}}
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
