kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  repo: {{.Repo}}
  branch: {{.Branch}}
  clientSecretName: {{.ClientSecretName}}
  # insecureSkipTLSVerify: true
  targetNamespace: {{.TargetNamespace}}
  paths:
  - simple
