kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: {{ .Repo }}
  branch: 1866-helm-oci-with-auth
  helmSecretName: {{ .SecretName }}
  paths:
  - {{ .Path }}
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
