kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  branch: add-helm-oci-with-auth-example
  helmSecretName: helm-oci-secret
  paths:
  - single-cluster/helm-oci-with-auth
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester