kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
    - target-customization-namespace-labels/without-default-values
