apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitjob
rules:
  - apiGroups:
      - "batch"
    resources:
      - 'jobs'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - 'pods'
    verbs:
      - 'list'
      - 'get'
      - 'watch'
  - apiGroups:
      - ""
    resources:
      - 'secrets'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - 'configmaps'
    verbs:
      - '*'
  - apiGroups:
      - "gitjob.cattle.io"
    resources:
      - "gitjobs"
      - "gitjobs/status"
    verbs:
      - "*"