apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitjob-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitjob
subjects:
  - kind: ServiceAccount
    name: gitjob
    namespace: {{ .Release.Namespace }}