apiVersion: v1
kind: Service
metadata:
  name: svc-test
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: svc-finalizer
  finalizers:
  - kubernetes
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-test
data:
  test.properties: |
    foo=bar
