apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-dummy-deployment
  labels:
    app: drift-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-dummy
  template:
    metadata:
      labels:
        app: drift-dummy
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        ports:
        - containerPort: 80
