// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1 (interfaces: ClusterGroupCache)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=internal/cmd/controller/mocks/cluster_group_cache_mock.go -package=mocks github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1 ClusterGroupCache
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1alpha1 "github.com/rancher/fleet/pkg/apis/fleet.cattle.io/v1alpha1"
	v1alpha10 "github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	labels "k8s.io/apimachinery/pkg/labels"
)

// MockClusterGroupCache is a mock of ClusterGroupCache interface.
type MockClusterGroupCache struct {
	ctrl     *gomock.Controller
	recorder *MockClusterGroupCacheMockRecorder
}

// MockClusterGroupCacheMockRecorder is the mock recorder for MockClusterGroupCache.
type MockClusterGroupCacheMockRecorder struct {
	mock *MockClusterGroupCache
}

// NewMockClusterGroupCache creates a new mock instance.
func NewMockClusterGroupCache(ctrl *gomock.Controller) *MockClusterGroupCache {
	mock := &MockClusterGroupCache{ctrl: ctrl}
	mock.recorder = &MockClusterGroupCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterGroupCache) EXPECT() *MockClusterGroupCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockClusterGroupCache) AddIndexer(arg0 string, arg1 v1alpha10.ClusterGroupIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockClusterGroupCacheMockRecorder) AddIndexer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockClusterGroupCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockClusterGroupCache) Get(arg0, arg1 string) (*v1alpha1.ClusterGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.ClusterGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterGroupCacheMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterGroupCache)(nil).Get), arg0, arg1)
}

// GetByIndex mocks base method.
func (m *MockClusterGroupCache) GetByIndex(arg0, arg1 string) ([]*v1alpha1.ClusterGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v1alpha1.ClusterGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockClusterGroupCacheMockRecorder) GetByIndex(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockClusterGroupCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockClusterGroupCache) List(arg0 string, arg1 labels.Selector) ([]*v1alpha1.ClusterGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*v1alpha1.ClusterGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterGroupCacheMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterGroupCache)(nil).List), arg0, arg1)
}
