// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/wrangler/pkg/generated/controllers/core/v1 (interfaces: ServiceAccountCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/rancher/wrangler/pkg/generated/controllers/core/v1"
	v10 "k8s.io/api/core/v1"
	labels "k8s.io/apimachinery/pkg/labels"
)

// MockServiceAccountCache is a mock of ServiceAccountCache interface.
type MockServiceAccountCache struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountCacheMockRecorder
}

// MockServiceAccountCacheMockRecorder is the mock recorder for MockServiceAccountCache.
type MockServiceAccountCacheMockRecorder struct {
	mock *MockServiceAccountCache
}

// NewMockServiceAccountCache creates a new mock instance.
func NewMockServiceAccountCache(ctrl *gomock.Controller) *MockServiceAccountCache {
	mock := &MockServiceAccountCache{ctrl: ctrl}
	mock.recorder = &MockServiceAccountCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountCache) EXPECT() *MockServiceAccountCacheMockRecorder {
	return m.recorder
}

// AddIndexer mocks base method.
func (m *MockServiceAccountCache) AddIndexer(arg0 string, arg1 v1.ServiceAccountIndexer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddIndexer", arg0, arg1)
}

// AddIndexer indicates an expected call of AddIndexer.
func (mr *MockServiceAccountCacheMockRecorder) AddIndexer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndexer", reflect.TypeOf((*MockServiceAccountCache)(nil).AddIndexer), arg0, arg1)
}

// Get mocks base method.
func (m *MockServiceAccountCache) Get(arg0, arg1 string) (*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceAccountCacheMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceAccountCache)(nil).Get), arg0, arg1)
}

// GetByIndex mocks base method.
func (m *MockServiceAccountCache) GetByIndex(arg0, arg1 string) ([]*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIndex", arg0, arg1)
	ret0, _ := ret[0].([]*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex.
func (mr *MockServiceAccountCacheMockRecorder) GetByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIndex", reflect.TypeOf((*MockServiceAccountCache)(nil).GetByIndex), arg0, arg1)
}

// List mocks base method.
func (m *MockServiceAccountCache) List(arg0 string, arg1 labels.Selector) ([]*v10.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*v10.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceAccountCacheMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceAccountCache)(nil).List), arg0, arg1)
}
