#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/flt dist/artifacts/flt-linux-${SUFFIX}
for i in bin/flt-*; do
    if [ -e "$i" ]; then
        cp $i dist/artifacts
    fi
done

IMAGE=${REPO}/fleet:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

if [ "$PUSH" = "true" ]; then
    docker push ${IMAGE}
fi

IMAGE=${REPO}/fleet-agent:${TAG}
DOCKERFILE=package/Dockerfile.agent
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

if [ "$PUSH" = "true" ]; then
    docker push ${IMAGE}
fi
