// Post-cleanup utility that runs after code generation to clean up unused imports
// in generated code. This was necessary for code generated by wrangler,
// which often introduces unused imports in the generated files. The tool uses
// goimports to automatically remove these unnecessary imports from the specified
// directories containing generated code, helping to avoid compilation errors about
// unused packages.
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	generatedDirs := []string{
		"./pkg/generated",
	}

	for _, dir := range generatedDirs {
		fmt.Printf("Cleaning up unused imports in %s\n", dir)

		// Run goimports to remove unused imports
		cmd := exec.Command("goimports", "-w", dir)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr

		if err := cmd.Run(); err != nil {
			fmt.Printf("Error running goimports: %v\n", err)
			os.Exit(1)
		}
	}

	fmt.Println("Post-cleanup completed successfully")
}
