---
apiVersion: v1
kind: Namespace
metadata:
  name: gitjob
---
apiVersion: v1
kind: Service
metadata:
  name: gitjob
  namespace: gitjob
spec:
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    gitjob: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjob
  namespace: gitjob
spec:
  selector:
    matchLabels:
      gitjob: "true"
  template:
    metadata:
      labels:
        gitjob: "true"
    spec:
      containers:
      - image: strongmonkey1992/gitjob:dev
        imagePullPolicy: Always
        name: gitjob
        command:
        - gitjob
      serviceAccountName: gitjob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitjob
  namespace: gitjob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitjob
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - '*'
  - apiGroups:
    - "batch"
    resources:
    - 'jobs'
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - 'secrets'
    verbs:
    - 'list'
    - 'get'
    - 'watch'
  - apiGroups:
    - ""
    resources:
    - 'configmaps'
    verbs:
    - 'create'
    - 'list'
    - 'get'
    - 'update'
  - apiGroups:
    - "gitjob.cattle.io"
    resources:
    - "gitjob"
    - "gitjob/status"
    verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitjob-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitjob
subjects:
  - kind: ServiceAccount
    name: gitjob
    namespace: gitjob
---


