---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjobs
  namespace: gitops
spec:
  selector:
    matchLabels:
      gitjobs: "true"
  template:
    metadata:
      labels:
        gitjobs: "true"
    spec:
      containers:
      - image: strongmonkey1992/gitjobs:dev
        imagePullPolicy: Always
        name: gitjobs
        command:
        - gitjobs
      serviceAccountName: gitjobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitjobs
  namespace: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitjobs
rules:
  - apiGroups:
    - "batch"
    resources:
    - 'jobs'
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - 'secrets'
    verbs:
    - 'list'
    - 'get'
    - 'watch'
  - apiGroups:
    - ""
    resources:
    - 'configmaps'
    verbs:
    - 'list'
    - 'get'
    - 'update'
  - apiGroups:
    - "gitops.cattle.io"
    resources:
    - "gitjobs"
    - "gitjobs/status"
    verbs:
    - "*"
  - apiGroups:
    - "gitops.cattle.io"
    resources:
    - "gitjobs"
    verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitjobs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitjobs
subjects:
  - kind: ServiceAccount
    name: gitjobs
    namespace: gitops
---

