# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed and restricted to,
# if not specified the chart will be installed to "default"
namespace: fleet-helm-oci-with-auth

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: sleeper-chart

  # The directory of the chart in the repo.  Any valid go-getter supported
  # URL can also be used here to specify where to download the chart from.
  # If repo below is set, this value is the chart name in the repo.
  chart: "oci://zot-service.default.svc.cluster.local:8082/sleeper-chart"

  # Used if repo is set to look up the version of the chart
  version: "0.1.0"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  values:
    replicas: 2
