apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-agent-simulator
spec:
  selector:
    matchLabels:
      app: fleet-agent-simulator
  template:
    metadata:
      labels:
        app: fleet-agent-simulator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: '{{.Values.image.repository}}:{{.Values.image.tag}}'
        args:
        - "fleetagent"
        - "--simulators={{.Values.simulators}}"
        name: fleet-agent-simulator
      serviceAccountName: fleet-agent
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

