kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{.Name}}
spec:
  repo: {{.Repo}}
  branch: {{.Branch}}
  pollingInterval: {{.PollingInterval}}
  {{- if .TargetNamespace }}
  targetNamespace: {{.TargetNamespace}}
  {{- end }}
  paths:
  - examples
