apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  labels:
    fleet: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
        - name: git-server
          image: nginx-git:test
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: post-receive-hook
            mountPath: /srv/git/repo/hooks/post-receive
            subPath: post-receive
      volumes:
        - name: post-receive-hook
          configMap:
            name: hook-script
            defaultMode: 0777 # hook must be executable
            items:
              - key: post-receive
                path: post-receive
