ARG SERVER_VERSION
FROM mcr.microsoft.com/powershell:lts-nanoserver-${SERVER_VERSION} AS BUILD
ARG RELEASES
ARG VERSION
ENV RELEASES=$RELEASES
ENV VERSION=$VERSION
SHELL ["pwsh", "-NoLogo", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN pushd c:\; \
    $URL = 'https://github.com/git-for-windows/git/releases/download/v2.33.1.windows.1/MinGit-2.33.1-64-bit.zip'; \
    \
    Write-Host ('Downloading git from {0} ...' -f $URL); \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-RestMethod -UseBasicParsing -OutFile c:\git.zip -Uri $URL; \
    \
    Write-Host 'Expanding ...'; \
    Expand-Archive -Force -Path c:\git.zip -DestinationPath c:\git\.; \
    \
    Write-Host 'Cleaning ...'; \
    Remove-Item -Force -Recurse -Path c:\git.zip; \
    \
    Write-Host 'Complete.'; \
    popd;
RUN $URL = 'https://{0}/fleet/{1}/fleetagent-windows-amd64.exe' -f $env:RELEASES, $env:VERSION; \
    New-Item -Path 'c:\\' -Name 'fleet' -ItemType 'directory'; \
    Write-Host ('Downloading fleet-agent from {0} ...' -f $URL); \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-RestMethod -UseBasicParsing -OutFile c:/fleet/fleetagent-windows.exe -Uri $URL;

FROM mcr.microsoft.com/windows/nanoserver:${SERVER_VERSION}

RUN mkdir "git" "fleet"
COPY --from=build c:/git/. c:/git/.
COPY --from=build c:/fleet/. c:/fleet/.

CMD ["C:\\fleet\\fleetagent-windows.exe"]
