ARG BUILD_ENV=dapper
ARG ARCH

FROM --platform=linux/$ARCH registry.suse.com/bci/bci-base:15.5 AS base
RUN zypper in --no-recommends -y git-core openssh; rm -fr /var/cache/* /var/log/*log
COPY package/log.sh /usr/bin/

FROM base AS copy_dapper
ONBUILD ARG ARCH
ONBUILD COPY bin/fleetagent-linux-$ARCH /usr/bin/fleetagent
ONBUILD COPY bin/fleet-linux-$ARCH /usr/bin/fleet

FROM base AS copy_buildx
ONBUILD ARG TARGETARCH
ONBUILD COPY bin/fleetagent-linux-$TARGETARCH /usr/bin/fleetagent
ONBUILD COPY bin/fleet-linux-$TARGETARCH /usr/bin/fleet

FROM base AS copy_goreleaser
ONBUILD ARG ARCH
ONBUILD COPY fleetagent-linux-$ARCH /usr/bin/fleetagent
ONBUILD COPY fleet-linux-$ARCH /usr/bin/fleet

FROM copy_${BUILD_ENV}
USER 1000
CMD ["fleetagent"]
