#!/bin/sh
set -x -e

k3s server \
   --disable-scheduler \
   --disable-cloud-controller \
   --disable-network-policy \
   --disable-agent \
   --no-deploy coredns,servicelb,traefik,local-storage,metrics-server &

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

while sleep 1; do
    if [ -e ${KUBECONFIG} ]; then
        break
    fi
    echo Waiting for k3s start
done

exec "$@" --kubeconfig ${KUBECONFIG}
