name: CI

on:
  schedule:
    - cron:  '0 5 * * *'
  pull_request:
  push:
    branches:
    - 'release/*'

env:
  GOARCH: amd64
  CGO_ENABLED: 0

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      -
        name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1
        with:
          version: v3.3.0
      -
        name: Run chart-testing (lint)
        run: ct lint --all --validate-maintainers=false charts/
      -
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
      -
        name: unit-test
        run: go test -shuffle=on $(go list ./... | grep -v -e /e2e -e /integrationtests -e /benchmarks)
      -
        name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      -
        name: integration-tests
        env:
          SETUP_ENVTEST_VER: v0.0.0-20250218120612-6f6111124902
          ENVTEST_K8S_VERSION: 1.32
        run: ./.github/scripts/run-integration-tests.sh
