name: Label issue
on:
  issues:
    types:
      - opened
      - reopened
      
permissions:
  issues: write
  
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        id: run
        run: gh issue edit -R ${GITHUB_REPOSITORY} --add-label ${LABEL} ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "team/fleet,area/fleet"
