name: Release Fleet against test Rancher charts repo
on:
  workflow_dispatch:
    inputs:
      charts_base_branch:
        description: "Use the following rancher/charts branch as a base (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.14"
        type: string
      charts_repo:
        description: "Push to the following Rancher charts repo (which must exist)"
        required: true
        default: "fleetrepoci/charts"
        type: string
      charts_target_branch:
        description: "Use the following branch as a destination when pushing to the charts repo"
        type: string
  workflow_call:
    # Variables to set when calling this reusable workflow
    inputs:
      charts_base_branch:
        description: "Use the following rancher/charts branch as a base (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.14"
        type: string
      charts_repo:
        description: "Push to the following Rancher charts repo (which must exist)"
        required: true
        default: "fleetrepoci/charts"
        type: string
      charts_target_branch:
        description: "Use the following branch as a destination when pushing to the charts repo"
        type: string
    secrets:
      CI_PUSH_TO_FLEETREPOCI:
        required: true
    outputs:
      target_branch:
        value: ${{ jobs.push-test-rancher-charts.outputs.target_branch }}
      charts_repo:
        value: ${{ jobs.push-test-rancher-charts.outputs.charts_repo }}

env:
  GOARCH: amd64

permissions:
  contents: write

jobs:
  push-test-rancher-charts:
    runs-on: ubuntu-latest

    outputs:
      target_branch: ${{ steps.compute_target_branch.outputs.target_branch }}
      charts_repo: ${{ steps.compute_env.outputs.charts_repo }}
    steps:
      - name: Set environment variables
        id: compute_env
        env:
          INPUT_CHARTS_BASE_BRANCH: ${{ inputs.charts_base_branch }}
          INPUT_CHARTS_REPO: ${{ inputs.charts_repo }}
        run: |
          charts_base_branch="${INPUT_CHARTS_BASE_BRANCH:-dev-v2.14}"
          charts_repo="${INPUT_CHARTS_REPO:-fleetrepoci/charts}"

          echo "charts_base_branch=$charts_base_branch" >> "$GITHUB_OUTPUT"
          echo "charts_repo=$charts_repo" >> "$GITHUB_OUTPUT"

      - name: Checkout rancher/fleet
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          path: fleet

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'fleet/go.mod'

      - name: Build fleet binaries
        run: |
          cd ./fleet
          ./.github/scripts/build-fleet-binaries.sh
          cd -

      - name: Get UUID
        id: uuid
        run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Extract metadata for Fleet controller image
        id: meta-fleet
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ttl.sh/rancher-fleet-${{ steps.uuid.outputs.uuid }}
          tags: type=raw,value=1h

      - name: Build and push Fleet controller image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ./fleet
          file: ./fleet/package/Dockerfile
          build-args: |
            ARCH=${{ env.GOARCH }}
          push: true
          tags: ${{ steps.meta-fleet.outputs.tags }}
          labels: ${{ steps.meta-fleet.outputs.labels }}

      - name: Extract metadata for Fleet agent image
        id: meta-fleet-agent
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ttl.sh/rancher-fleet-agent-${{ steps.uuid.outputs.uuid }}
          tags: type=raw,value=1h

      - name: Build and push Fleet agent image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ./fleet
          file: ./fleet/package/Dockerfile.agent
          build-args: |
            ARCH=${{ env.GOARCH }}
          push: true
          tags: ${{ steps.meta-fleet-agent.outputs.tags }}
          labels: ${{ steps.meta-fleet-agent.outputs.labels }}

      - name: Checkout test charts repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          token: ${{secrets.CI_PUSH_TO_FLEETREPOCI}}
          repository: ${{ steps.compute_env.outputs.charts_repo }}
          path: charts

      - name: Compute target branch name
        id: compute_target_branch
        env:
          INPUT_CHARTS_TARGET_BRANCH: ${{ inputs.charts_target_branch }}
          EVENT_NAME: ${{ github.event_name }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH: ${{ steps.compute_env.outputs.charts_base_branch }}
        run: |
          target_branch_name="${INPUT_CHARTS_TARGET_BRANCH:-}"

          if [ "$EVENT_NAME" = 'pull_request' ]; then
            target_branch_name="$PR_HEAD_REF"
          elif [ -z "$target_branch_name" ]; then
            target_branch_name="$BASE_BRANCH-$(date +%Y%m%d%H%M%S)"
          fi

          # Append prefix if not present
          prefix='fleetci-'
          if [[ "$target_branch_name" != "$prefix"* ]]; then
            target_branch_name="$prefix$target_branch_name"
          fi

          echo "target_branch=$target_branch_name" >> "$GITHUB_OUTPUT"

      - name: Set up test charts repo with latest upstream state
        env:
          TARGET_BRANCH: ${{steps.compute_target_branch.outputs.target_branch}}
          BASE_BRANCH: ${{steps.compute_env.outputs.charts_base_branch}}
        run: |
          cd charts
          # Add upstream remote and fetch from it
          # Name it `origin` for compatibility with `make pull-scripts`
          git remote rename origin fleetoci
          git remote add -f origin https://github.com/rancher/charts

          target_branch="$TARGET_BRANCH"
          base_branch="$BASE_BRANCH"

          git checkout -b "$target_branch" "origin/$base_branch"
          if [ $? -eq 128 ]; then # branch already exists
            git checkout "$target_branch"
            git rebase "origin/$base_branch"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y --allow-change-held-packages snapd
          sudo snap install yq --channel=v4/stable

      - name: Run release script
        env:
          UUID: ${{ steps.uuid.outputs.uuid }}
        run: |
          fleet_test_version=9.9.9

          latest_fleet_rancher_version=$(ls ./charts/charts/fleet/ | tail -1)
          latest_chart="${latest_fleet_rancher_version%%+*}"
          latest_fleet="${latest_fleet_rancher_version#*+up}"

          ./fleet/.github/scripts/release-against-test-charts.sh \
            "$latest_fleet" \
            "$fleet_test_version" \
            "$latest_chart" \
            "999.9.9" \
            "$UUID"

      - name: Push to custom branch
        env:
          TARGET_BRANCH: ${{ steps.compute_target_branch.outputs.target_branch }}
        run: |
          cd charts
          git push -u fleetoci "$TARGET_BRANCH"
