name: Test Typos
on: [pull_request]

permissions:
  contents: read

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Check spelling of file.txt
      uses: crate-ci/typos@7b04f660f4ee4f048d18fd341887cf28dfbedfe2 # v1.46.3

