---
name: "Updatecli: Dependency Management"

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day
    - cron: '0 1 * * *'

permissions:
  contents: read
  pull-requests: read

jobs:
  updatecli:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf # v3.3.0

      - name: Apply
        run: "updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.d/scm.yaml"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
